### ISSUE TITLE
Technical issue, data entry: Situation page gets really wide

### ISSUE THREAD

**Issue by mareinna** [jilltxt/machinevision#73] opened 2019-11-14 13:24 UTC
When we open a situation the page get really wide, probably as a result of the descriptions/explanations of the different elements, or because the text we enter into the text boxes don't wrap. This makes the data entry page difficult to navigate. Is there a way make the text wrap to the page instead of continually expanding the box?

EDIT FROM JILL: Caused by help texts not wrapping?

**Comment by jilltxt** [comment] 2019-11-15 11:53
When I open it in Safari it looks like this:

<img width="784" alt="Screen Shot 2019-11-15 at 12 47 54" src="https://user-images.githubusercontent.com/44365847/68941450-3433d880-07a6-11ea-8b0b-5283fe2da308.png">

So my window doesn't go wide, but the help texts aren't wrapping. I am guessing that in some browsers, the long help texts force the window to go wide? I don't know how to make the help text wrap but I am pretty sure it used to.

**Comment by jilltxt** [comment] 2020-01-24 12:41
It's caused by the paragraphs using a table. Check after migration: is this solved?

**Comment by jilltxt** [comment] 2020-01-24 12:44
@steinmb will provide @jilltxt with specs, and @jilltxt will put in an order for the virtual server.

**Comment by steinmb** [comment] 2020-05-19 11:33
Closing this. Was addressed by this in april:

commit 1b2bae66f3d16bff37d195da021246e6ab9f01e8 (HEAD -> master)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Tue Apr 21 11:32:40 2020 +0200

    Improve editing node forms in seven

    - Some tax term lists of checkboxes split in two col. to reduce
    vertical space.
    - Try to stop paragraphs from horisontal overflowing container in node forms.

**Closed as completed by steinmb** 2020-05-19 11:33 UTC
Labels: post-migration
